# Generated by Django 3.2.6 on 2021-08-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210710_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cant_partidos',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='goles_local',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='goles_visita',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='victorias_local',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='victorias_visita',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
