# Generated by Django 3.2.6 on 2021-09-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210828_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competicion', models.ImageField(upload_to='')),
                ('fecha', models.CharField(max_length=5)),
                ('local', models.CharField(max_length=100)),
                ('visit', models.CharField(max_length=100)),
                ('imglocal', models.ImageField(upload_to='')),
                ('imgvisit', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='competicion',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='match',
            name='imglocal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='imgvisit',
        ),
        migrations.RemoveField(
            model_name='match',
            name='local',
        ),
        migrations.RemoveField(
            model_name='match',
            name='visit',
        ),
    ]
