# Generated by Django 3.2.6 on 2021-09-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210901_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='visit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
