# Generated by Django 3.2.6 on 2021-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210901_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='empates',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
