# Generated by Django 3.2.6 on 2021-10-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_match_empates'),
    ]

    operations = [
        migrations.AddField(
            model_name='previa',
            name='estadio',
            field=models.CharField(default='Estadio Campeón Del Siglo', max_length=100),
            preserve_default=False,
        ),
    ]
